---
title: "map - example"
author: "Dr Maria Prokofieva"
date: "03/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## interactive map example


```{r echo=FALSE, message=FALSE}

library(leaflet)

library(tidyverse)

data<-read_csv("data/map_research.csv")

data<-data %>% 
    mutate(popup = paste0('<a href =', description, '>', "Link", '</a>'))


academic<-data%>%filter(type=="Academic Collaborators")
industry<-data%>%filter(type=="National Industry Collaborators")
national_academic<-data%>%filter(type=="Australian/ National Academic Collaborators")


leaflet() %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite")%>%

# addLayersControl(overlayGroups = c("type"))%>%
  
   addMarkers(data = academic, group = "Academic Collaborators", label = academic$name, 
             lng=academic$lng,
             lat=academic$lat,
           popup = academic$popup) %>%
  addMarkers(data = industry, group = "National Industry Collaborators", label = industry$name, 
             lng=industry$lng,
             lat=industry$lat,
           popup = industry$popup) %>%
  addMarkers(data = national_academic, group = "Australian/ National Academic Collaborators",
             label = national_academic$name, 
             lng=national_academic$lng,
             lat=national_academic$lat,
           popup = national_academic$popup)%>%
  addLayersControl(overlayGroups = c("Academic Collaborators", "National Industry Collaborators", "Australian/ National Academic Collaborators"),
    options = layersControlOptions(collapsed = FALSE))

```

